"""create core tables

Revision ID: d06cbf4b0231
Revises: 
Create Date: 2026-06-04 17:51:32.520476
"""

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql


revision: str = 'd06cbf4b0231'
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('email', sa.String(length=320), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default=sa.text('(true)'), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_table('system_templates',
    sa.Column('owner_user_id', sa.Uuid(), nullable=True),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('slug', sa.String(length=160), nullable=False),
    sa.Column('type', sa.String(length=50), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('is_builtin', sa.Boolean(), server_default=sa.text('(false)'), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('metadata_json', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), server_default=sa.text("'{}'"), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('archived_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['owner_user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_system_templates_owner_user_id'), 'system_templates', ['owner_user_id'], unique=False)
    op.create_index(op.f('ix_system_templates_slug'), 'system_templates', ['slug'], unique=False)
    op.create_table('worlds',
    sa.Column('owner_user_id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('slug', sa.String(length=160), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=50), server_default=sa.text("'active'"), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('metadata_json', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), server_default=sa.text("'{}'"), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('archived_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['owner_user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('owner_user_id', 'slug', name='uq_worlds_owner_user_id_slug')
    )
    op.create_index(op.f('ix_worlds_owner_user_id'), 'worlds', ['owner_user_id'], unique=False)
    op.create_table('game_projects',
    sa.Column('owner_user_id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('slug', sa.String(length=160), nullable=False),
    sa.Column('format', sa.String(length=50), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=50), server_default=sa.text("'active'"), nullable=False),
    sa.Column('system_template_id', sa.Uuid(), nullable=True),
    sa.Column('world_id', sa.Uuid(), nullable=True),
    sa.Column('theme', sa.String(length=50), server_default=sa.text("'cartographer'"), nullable=False),
    sa.Column('cover_image_url', sa.String(length=2048), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('metadata_json', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), server_default=sa.text("'{}'"), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('archived_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['owner_user_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['system_template_id'], ['system_templates.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['world_id'], ['worlds.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('owner_user_id', 'slug', name='uq_game_projects_owner_user_id_slug')
    )
    op.create_index(op.f('ix_game_projects_owner_user_id'), 'game_projects', ['owner_user_id'], unique=False)
    op.create_index(op.f('ix_game_projects_system_template_id'), 'game_projects', ['system_template_id'], unique=False)
    op.create_index(op.f('ix_game_projects_world_id'), 'game_projects', ['world_id'], unique=False)
    op.create_table('project_module_settings',
    sa.Column('game_project_id', sa.Uuid(), nullable=False),
    sa.Column('module_key', sa.String(length=100), nullable=False),
    sa.Column('display_name', sa.String(length=120), nullable=False),
    sa.Column('is_enabled', sa.Boolean(), server_default=sa.text('(true)'), nullable=False),
    sa.Column('order_index', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('icon_key', sa.String(length=80), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['game_project_id'], ['game_projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('game_project_id', 'module_key', name='uq_project_module_settings_game_project_id_module_key')
    )
    op.create_index(op.f('ix_project_module_settings_game_project_id'), 'project_module_settings', ['game_project_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_project_module_settings_game_project_id'), table_name='project_module_settings')
    op.drop_table('project_module_settings')
    op.drop_index(op.f('ix_game_projects_world_id'), table_name='game_projects')
    op.drop_index(op.f('ix_game_projects_system_template_id'), table_name='game_projects')
    op.drop_index(op.f('ix_game_projects_owner_user_id'), table_name='game_projects')
    op.drop_table('game_projects')
    op.drop_index(op.f('ix_worlds_owner_user_id'), table_name='worlds')
    op.drop_table('worlds')
    op.drop_index(op.f('ix_system_templates_slug'), table_name='system_templates')
    op.drop_index(op.f('ix_system_templates_owner_user_id'), table_name='system_templates')
    op.drop_table('system_templates')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
